---
- name: "Run linchpin_libvirt container"
  hosts: localhost
  connection: local
  tasks:
    - name: "Create directory"
      file:
        path: "/tmp/linchpintest"
        state: directory
    - name: "Run linchpin init on folder"
      shell: "linchpin init"
      args:
        chdir: /tmp/linchpintest
      ignore_errors: yes
    - name: "Template out Pinfile"
      template:
        src: PinFile
        dest: /tmp/linchpintest/PinFile
    - name: "Template out topology"
      template:
        src: example-topology.yml
        dest: /tmp/linchpintest/topologies/example-topology.yml
    - name: "Create the docker container"
      docker_container:
        name: mylibvirtrun
        image: samvaran/linchpin_libvirt_container
        volumes:
          - /tmp/linchpintest:/tmp/linchpintest
        command: 'tail -f /dev/null'
        detach: yes
    - name: "Docker exec for running"
      docker_exec:
        command: "cat /root/.ssh/id_rsa.pub "
        name: mylibvirtrun
      register: exec_output
    - name: add line to authorized keys
      lineinfile:
        dest: "~/.ssh/authorized_keys"
        line: "{{ exec_output.result | strip('\n')  }}"

